// The single list of capabilities. `ve capabilities` renders it, and
// `bin/ve.mjs` dispatches from it.
//
// STATUS IS NOT SELF-DECLARED. A tool may claim `status: 'working'` here, but
// `ve capabilities` downgrades it to "untested" unless tests/.results/latest.json
// shows its suite actually passing. Implemented + executed + validated, or it
// does not count.

/** @typedef {'working'|'experimental'|'planned'|'failed'} Status */

export const TOOLS = [
  {
    name: 'probe-video',
    file: 'probe-video.mjs',
    capability: 'Video probe',
    phase: 1,
    status: 'working',
    tests: 'probe-video.test.mjs',
    summary: 'Technical metadata: duration, resolution, fps, codecs, rotation.',
  },
  {
    name: 'extract-audio',
    file: 'extract-audio.mjs',
    capability: 'Audio extraction',
    phase: 1,
    status: 'working',
    tests: 'extract-audio.test.mjs',
    summary: 'Speech-ready 16 kHz mono PCM WAV, cached by content hash.',
  },
  {
    name: 'cut-video',
    file: 'cut-video.mjs',
    capability: 'Cut engine',
    phase: 1,
    status: 'working',
    tests: 'cut-video.test.mjs',
    summary: 'Keep/remove time ranges and concatenate, preserving A/V sync.',
  },
  {
    name: 'transcribe',
    file: 'transcribe.mjs',
    capability: 'Transcription (word timestamps)',
    phase: 2,
    status: 'working',
    tests: 'transcribe.test.mjs',
    requires: 'python',
    summary: 'Speech to text with word-level timestamps via faster-whisper.',
  },
  {
    name: 'detect-silence',
    file: 'detect-silence.mjs',
    capability: 'Silence detection',
    phase: 2,
    status: 'working',
    tests: 'detect-silence.test.mjs',
    summary: 'Silent stretches plus their complementary speech regions.',
  },
  {
    name: 'detect-scenes',
    file: 'detect-scenes.mjs',
    capability: 'Scene detection',
    phase: 2,
    status: 'working',
    tests: 'detect-scenes.test.mjs',
    summary: 'Hard-cut detection via ffmpeg scdet; splits video into shots.',
  },
  {
    name: 'extract-frames',
    file: 'extract-frames.mjs',
    capability: 'Frame extraction',
    phase: 2,
    status: 'working',
    tests: 'extract-frames.test.mjs',
    summary: 'Still frames by interval, timestamp, scene or a smart mix.',
  },
  {
    name: 'remove-silence',
    file: 'remove-silence.mjs',
    capability: 'Silence removal',
    phase: 3,
    status: 'working',
    tests: 'remove-silence.test.mjs',
    summary: 'Cut out pauses at three intensities, optionally snapping to word boundaries.',
  },
  {
    name: 'crop-video',
    file: 'crop-video.mjs',
    capability: 'Crop / resize / reframe',
    phase: 3,
    status: 'working',
    tests: 'crop-video.test.mjs',
    summary: 'Aspect conversion (16:9 -> 9:16), resize, letterbox with blurred fill.',
  },
  {
    name: 'zoom-video',
    file: 'zoom-video.mjs',
    capability: 'Zoom engine',
    phase: 3,
    status: 'working',
    tests: 'zoom-video.test.mjs',
    summary: 'Timed smooth/punch/linear zooms with eased ramps and focal points.',
  },
  {
    name: 'change-speed',
    file: 'change-speed.mjs',
    capability: 'Speed change',
    phase: 3,
    status: 'working',
    tests: 'change-speed.test.mjs',
    summary: 'Retime video and audio together, preserving pitch by default.',
  },
  {
    name: 'normalize-audio',
    file: 'normalize-audio.mjs',
    capability: 'Audio normalisation',
    phase: 3,
    status: 'working',
    tests: 'normalize-audio.test.mjs',
    summary: 'Two-pass EBU R128 loudness normalisation; video stream-copied.',
  },
  {
    name: 'captions',
    file: 'captions.mjs',
    capability: 'Captions',
    phase: 4,
    status: 'working',
    tests: 'captions.test.mjs',
    requires: 'python',
    summary: 'Word-timed styled subtitles (.ass) in 5 presets; optional burn-in.',
  },
  {
    name: 'detect-keywords',
    file: 'detect-keywords.mjs',
    capability: 'Keyword detection',
    phase: 4,
    status: 'working',
    tests: 'keywords-fillers.test.mjs',
    requires: 'python',
    summary: 'Rank words to highlight, from emphasis, rarity and word shape.',
  },
  {
    name: 'remove-fillers',
    file: 'remove-fillers.mjs',
    capability: 'Filler-word removal',
    phase: 4,
    status: 'working',
    tests: 'keywords-fillers.test.mjs',
    requires: 'python',
    summary: 'Conservative removal of hesitations and stutters, by word timing.',
  },
  {
    name: 'smart-crop',
    file: 'smart-crop.mjs',
    capability: 'Vertical smart crop',
    phase: 4,
    status: 'working',
    tests: 'smart-crop.test.mjs',
    requires: 'python',
    summary: 'Face-tracked reframing to 9:16, with smoothing and a deadzone.',
  },
  {
    name: 'add-sfx',
    file: 'add-sfx.mjs',
    capability: 'Sound effects',
    phase: 4,
    status: 'working',
    tests: 'add-sfx.test.mjs',
    summary: 'Mix effects at timestamps, density-limited and ducked under speech.',
  },
  {
    name: 'add-overlay',
    file: 'add-overlay.mjs',
    capability: 'Overlays / images / memes',
    phase: 7,
    status: 'working',
    tests: 'add-overlay.test.mjs',
    summary: 'Composite images, GIFs or clips with position, timing and animation.',
  },
  {
    name: 'validate-edit-plan',
    file: 'validate-edit-plan.mjs',
    capability: 'Edit plan + validator',
    phase: 6,
    status: 'working',
    tests: 'edit-plan.test.mjs',
    summary: 'Schema, source-time timeline mapping, and pre-render validation.',
  },
  {
    name: 'render-edit',
    file: 'render-edit.mjs',
    capability: 'Render engine',
    phase: 6,
    status: 'working',
    tests: 'render-edit.test.mjs',
    summary: 'Execute a plan stage by stage, reusing cached intermediates.',
  },
  {
    name: 'preview-edit',
    file: 'preview-edit.mjs',
    capability: 'Preview render',
    phase: 6,
    status: 'working',
    tests: 'render-edit.test.mjs',
    summary: 'Fast reduced-size render of the same plan, for checking decisions.',
  },
  {
    name: 'qa-video',
    file: 'qa-video.mjs',
    capability: 'Automatic QA',
    phase: 6,
    status: 'working',
    tests: 'qa-video.test.mjs',
    summary: 'Streams, geometry, duration, A/V sync, black frames, audio levels.',
  },
  {
    name: 'contact-sheet',
    file: 'contact-sheet.mjs',
    capability: 'Contact sheet',
    phase: 6,
    status: 'working',
    tests: 'qa-video.test.mjs',
    summary: 'One image of evenly spaced frames for a quick visual check.',
  },
  {
    name: 'edit-video',
    file: 'edit-video.mjs',
    capability: 'Orchestrator + reasoning log',
    phase: 6,
    status: 'working',
    tests: 'edit-video.test.mjs',
    requires: 'python',
    summary: 'Analyse, plan, validate, render and QA in one command.',
  },
  {
    name: 'denoise-audio', file: 'denoise-audio.mjs', capability: 'Denoise audio',
    phase: 8, status: 'working', tests: 'audio-fx.test.mjs',
    summary: 'Spectral denoise with a MEASURED noise floor, not a guessed one.',
  },
  {
    name: 'compress-voice', file: 'compress-voice.mjs', capability: 'Voice compression',
    phase: 8, status: 'working', tests: 'audio-fx.test.mjs',
    summary: 'Even out speech dynamics; verified by crest-factor reduction.',
  },
  {
    name: 'add-music', file: 'add-music.mjs', capability: 'Background music',
    phase: 8, status: 'working', tests: 'audio-fx.test.mjs',
    summary: 'Music bed, looped and faded, ducked under speech by default.',
  },
  {
    name: 'duck-music', file: 'duck-music.mjs', capability: 'Music ducking under speech',
    phase: 8, status: 'working', tests: 'audio-fx.test.mjs',
    summary: 'Sidechain a separate music track under the voice.',
  },
  {
    name: 'freeze-frame', file: 'freeze-frame.mjs', capability: 'Freeze frame',
    phase: 8, status: 'working', tests: 'video-fx.test.mjs',
    summary: 'Hold a frame, extending the video by exactly the hold.',
  },
  {
    name: 'blur-region', file: 'blur-region.mjs', capability: 'Blur region (faces, secrets)',
    phase: 8, status: 'working', tests: 'video-fx.test.mjs',
    summary: 'Blur, pixelate or black out part of the frame; optional face mode.',
  },
  {
    name: 'transitions', file: 'transitions.mjs', capability: 'Transitions',
    phase: 8, status: 'working', tests: 'video-fx.test.mjs',
    summary: 'Join clips with xfade, or dip/flash at a cut. Hard cut stays default.',
  },
  {
    name: 'background', file: 'background.mjs', capability: 'Background blur / replace',
    phase: 8, status: 'working', tests: 'video-fx.test.mjs', requires: 'python',
    summary: 'Vignette without a model; blur/darken/replace via segmentation.',
  },
  {
    name: 'track-faces', file: 'track-faces.mjs', capability: 'Face / speaker tracking',
    phase: 7, status: 'working', tests: 'analysis.test.mjs', requires: 'python',
    summary: 'Face positions over time, smoothed subject track, shot classification.',
  },
  {
    name: 'analyze-visual', file: 'analyze-visual.mjs', capability: 'Visual analysis',
    phase: 7, status: 'working', tests: 'analysis.test.mjs',
    summary: 'Motion, brightness, faces and scenes as a per-timestamp timeline.',
  },
  {
    name: 'add-broll', file: 'add-broll.mjs', capability: 'B-roll insertion',
    phase: 7, status: 'working', tests: 'analysis.test.mjs',
    summary: 'Cut away to supporting footage; can suggest placements from the transcript.',
  },
  {
    name: 'analyze-style', file: 'analyze-style.mjs', capability: 'Style analysis from references',
    phase: 7, status: 'working', tests: 'analysis.test.mjs',
    summary: 'Abstract editing rhythm of a reference, mapped to a style preset.',
  },
  {
    name: 'modes', file: 'modes.mjs', capability: 'Editing modes (clean/viral/podcast/coding)',
    phase: 9, status: 'working', tests: 'edit-plan.test.mjs',
    summary: 'Six style presets in lib/styles.mjs, overridable from styles/*.json.',
  },
  {
    name: 'nl-edit', file: 'nl-edit.mjs', capability: 'Natural-language plan editing',
    phase: 9, status: 'working', tests: 'nl-edit.test.mjs',
    summary: 'Change an edit plan from an instruction, or from a precise path expression.',
  },
  {
    name: 'commands', file: null, capability: 'High-level slash commands',
    phase: 9, status: 'working', tests: 'interface.test.mjs',
    summary: '/edit /preview /transcribe /cut-silence /captions /vertical in .claude/commands/.',
  },
  {
    name: 'skills', file: null, capability: 'Claude Code Skills',
    phase: 9, status: 'working', tests: 'interface.test.mjs',
    summary: '.claude/skills/video-editor/SKILL.md — how to drive the toolkit.',
  },
  {
    name: 'remotion-render', file: 'remotion-render.mjs',
    capability: 'Remotion motion graphics',
    phase: 5, status: 'working', tests: 'remotion.test.mjs',
    summary: '16-component library rendered to transparent overlays for compositing.',
  },
  {
    name: 'code-visuals', file: null, capability: 'Code / terminal / browser visuals',
    phase: 5, status: 'working', tests: 'remotion.test.mjs',
    summary: 'CodeBlock, Terminal, BrowserWindow, CodeDiff, PhoneFrame in the Remotion library.',
  },
];

/** Capabilities on the roadmap but not yet built. Keeps `capabilities` honest. */
export const PLANNED = [
  // Phase 6 — intelligent editing


  // Phase 9 — the interface
];

export const byName = name => TOOLS.find(t => t.name === name);
